import type { PropsWithChildren } from 'react';
import { Image, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { Feather } from '@expo/vector-icons';
import { router } from 'expo-router';
import { colors, fonts } from '../theme';
import { ComicEdges } from './ComicEdges';
import type { Teammate } from '../data/agents';
export function Page({ children }: PropsWithChildren) { return <SafeAreaView edges={['top']} style={s.page}><ComicEdges /><ScrollView contentContainerStyle={s.content} keyboardShouldPersistTaps="handled"><Header />{children}</ScrollView></SafeAreaView>; }
export function Header() { return <View style={s.header}><Text style={s.brand}>FAREEQ AI</Text><Pressable accessibilityRole="button" accessibilityLabel="Your account" onPress={() => router.push('/account')} style={s.profile}><Feather name="user" size={22} color={colors.navy} /></Pressable></View>; }
export function Heading({ children }: PropsWithChildren) { return <Text style={s.heading}>{children}</Text>; }
export function Body({ children }: PropsWithChildren) { return <Text style={s.body}>{children}</Text>; }
export function Portrait({ agent, size = 60 }: { agent: Teammate; size?: number }) { return <Image source={agent.art} accessibilityLabel={agent.name} style={{ width: size, height: size, borderRadius: size / 2, borderWidth: 2, borderColor: colors.ink, backgroundColor: colors.gold }} />; }
export function AgentCard({ agent, compact = false }: { agent: Teammate; compact?: boolean }) { return <Pressable accessibilityRole="button" accessibilityLabel={`Talk to ${agent.name}, ${agent.role}`} onPress={() => router.push({ pathname: '/agents/[id]', params: { id: agent.id } })} style={({ pressed }) => [s.card, { opacity: pressed ? 0.75 : 1, padding: compact ? 10 : 12, gap: compact ? 7 : 10 }]}><Portrait agent={agent} size={compact ? 40 : 52} /><View style={{ flex: 1 }}><Text style={[s.nameTab, compact && { fontSize: 14, paddingHorizontal: 5 }]}>{agent.name}</Text><Text style={[s.role, compact && { fontSize: 12 }]}>{agent.role}</Text></View>{!compact && <Feather name="chevron-right" size={17} color={colors.navy} />}</Pressable>; }
export const s = StyleSheet.create({ page: { flex: 1, backgroundColor: colors.paper }, content: { paddingHorizontal: 24, paddingBottom: 28, gap: 18, width: '100%', maxWidth: 720, alignSelf: 'center' }, header: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingVertical: 15, borderBottomWidth: 1, borderBottomColor: '#D4CEBD' }, brand: { fontFamily: fonts.brand, color: colors.ink, fontSize: 25, borderBottomWidth: 3, borderBottomColor: colors.pink }, profile: { width: 44, height: 44, borderWidth: 2, borderColor: colors.ink, borderRadius: 22, alignItems: 'center', justifyContent: 'center' }, heading: { fontFamily: fonts.heading, fontSize: 29, color: colors.ink }, body: { fontFamily: fonts.body, color: colors.secondaryText, fontSize: 15, lineHeight: 23 }, card: { backgroundColor: colors.reading, borderColor: colors.ink, borderWidth: 2, borderRadius: 12, padding: 12, flexDirection: 'row', gap: 10, alignItems: 'center', minHeight: 92 }, nameTab: { fontFamily: fonts.bold, fontSize: 17, color: colors.ink, backgroundColor: colors.gold, borderWidth: 1.5, borderColor: colors.ink, borderRadius: 6, paddingHorizontal: 8, paddingVertical: 3, alignSelf: 'flex-start' }, role: { fontFamily: fonts.body, fontSize: 13, color: colors.navy, marginTop: 6 }, button: { minHeight: 48, borderWidth: 2, borderColor: colors.ink, backgroundColor: colors.gold, borderRadius: 10, padding: 12, alignItems: 'center', justifyContent: 'center' }, buttonText: { fontFamily: fonts.bold, color: colors.ink, fontSize: 15 }, field: { minHeight: 48, backgroundColor: colors.reading, borderColor: colors.ink, borderWidth: 2, borderRadius: 12, padding: 12, fontFamily: fonts.body, color: colors.ink, fontSize: 15 }, section: { fontFamily: fonts.bold, color: colors.ink, fontSize: 19 }, row: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }, grid: { flexDirection: 'row', flexWrap: 'wrap', gap: 12 }, tile: { flexBasis: '47%', flexGrow: 1 }, note: { fontFamily: fonts.body, fontSize: 12, lineHeight: 18, color: colors.secondaryText } });
